#! /usr/bin/env python
import os
from argparse import ArgumentParser
from pathlib import Path

from walker.upscale import upscale



def main(cfg):
    os.chdir(f"./results/{cfg.folder}")
    upscale()


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument(dest="folder", choices=list(map(lambda x: x.stem, Path("./results/").glob("*"))))
    parser.add_argument("-device", type=str, required=True)
    parser.add_argument("-fps", type=int, default=60)
    main(parser.parse_args())
